package webservice;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-10-17T10:42:47.285+02:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "SampleService", 
                  wsdlLocation = "classpath:SampleService_V01.wsdl",
                  targetNamespace = "http://private.domain.at/Webservice/") 
public class SampleService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://private.domain.at/Webservice/", "SampleService");
    public final static QName SampleServicePort = new QName("http://private.domain.at/Webservice/", "SampleServicePort");
    static {
        URL url = SampleService_Service.class.getClassLoader().getResource("SampleService_V01.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(SampleService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:SampleService_V01.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public SampleService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SampleService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SampleService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SampleService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SampleService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SampleService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns SampleService
     */
    @WebEndpoint(name = "SampleServicePort")
    public SampleService getSampleServicePort() {
        return super.getPort(SampleServicePort, SampleService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SampleService
     */
    @WebEndpoint(name = "SampleServicePort")
    public SampleService getSampleServicePort(WebServiceFeature... features) {
        return super.getPort(SampleServicePort, SampleService.class, features);
    }

}
