package webservice;

import at.struct.wasbug23.DateAdater;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-10-17T10:42:47.225+02:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://private.domain.at/Webservice/", name = "SampleService")
@XmlSeeAlso({ObjectFactory.class})
public interface SampleService {

    @WebMethod
    @RequestWrapper(localName = "getData", targetNamespace = "http://private.domain.at/Webservice/", className = "at.domain._private.webservice.GetData")
    @ResponseWrapper(localName = "getDataResponse", targetNamespace = "http://private.domain.at/Webservice/", className = "at.domain._private.webservice.GetDataResponse")
    @WebResult(name = "getDataResponse", targetNamespace = "")
    public java.util.List<webservice.GetDataDTO> getData(
        @WebParam(name = "zugriffstag", targetNamespace = "")
        org.joda.time.LocalDate zugriffstag
    );
}
